name: enix
description: An Eludris API wrapper for Dart.
version: 0.1.0
repository: https://github.com/eludris-community/enix

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  http: ^0.13.5
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
